### PR TITLE
 LPP-32543 Added check for empty variable value

### PR DESCRIPTION
**Pull request by noemi-zamarripa**
https://issues.liferay.com/browse/LPP-32543

Issue:
Copy-Paste not functioning as expected in IE11. 

Fix:
Added a check for an empty variable which was causing the code to fail and copy-paste in IE11 to misbehave.

### CODE REVIEW

**Comment by noemi-zamarripa** [comment]
ci:test:sf

**Comment by noemi-zamarripa** [comment]
ci:test:relevant

**Comment by gregory-bretall** [comment]
I think we should be able to get the same logic without the else since we're returning if the if condition is true. Could you make that change and then resend the PR to @blzaugg for further review. Thanks!

**Comment by noemi-zamarripa** [comment]
Sure thanks!

**Pull request closed without merging**
